pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git url: 'git@github.com:winnieKM/alx-backend-python.git', branch: 'main'
                
                echo 'Current Git branch:'
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies...'
                sh 'pip3 install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests with pytest...'
                sh 'pytest > result.log || true'
            }
        }

        stage('Archive Results') {
            steps {
                echo 'Archiving test results...'
                archiveArtifacts artifacts: 'result.log', onlyIfSuccessful: false
            }
        }
    }
}
