pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository...'
                git credentialsId: 'github-ssh-key', url: 'git@github.com:winnieKM/alx-backend-python.git'
                // ✅ REQUIRED by ALX
                sh 'git branch'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app/tests/'
            }
        }

        stage('Archive Results') {
            steps {
                junit 'messaging_app/tests/test-reports/*.xml'
            }
        }
    }
}
