#!/bin/bash

echo "Deploying blue and green versions..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml

echo "Applying service to point to green version..."
kubectl apply -f kubeservice.yaml

echo "Checking logs for green deployment..."
GREEN_POD=$(kubectl get pods -l app=messaging-app-green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"
